services:
  db:
    image: postgres:16
    container_name: corae_db
    restart: always
    environment:
      POSTGRES_USER: coraeapp
      POSTGRES_PASSWORD: corAe1
      POSTGRES_DB: corae
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: corae_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: